language: java
sudo: false
jdk:
- openjdk11
env:
  global:
  - secure: "LT4nMSKCu4qL+jQ80BdBIOqFO3GCyAPoxNkskS0q0wvscDpEx2bvFZa9KF6/dQxubhWnfACqWxxPKfF3VadfZoKn1z01TaZ/rKHkA5GedZweFO0wBIvi/gDIcAxVX0oPOkIruugYY3iDOzOqTUuBM686cW1XWs0LEV7qPTb6KM02/IeckQs+P9SSiarqSKROlQ8dABGdyxJTXheHHphFu4mDiQsi1vtub6OoQclKLLuK2MJvFiyDeZDYYXAnjFNC/pcBUBjr5b886zPB6HLLGgvQKRLvzQudedz08ZlJdnt3k6u7HvLINbs00U60fnD/+4krQQN4EEx0Natv4L1SxFjYO4wFK2FTCKoBMkVfjINqiWzmb/yhoG33Sw9VGiYdcV45QbH32CX1oiATohV+79gfIID6p3UOL1SZuELR2XzRq70K4Kw2BXig99a0+LjYCv4ynnzetqyWVZIdhBQ1Srf/4GxUwF21Urn9TJCNr2F5BcbqGrMUMvXNjTI0WqQCTMqM+Ha9Rbe27GG7ZMtMUHd83YWP0GDiSIg2S0T0lNL2e9iQGXsGBiX3Bz+E3HEWhnE4l6XKYVgn3NXrlDjwc2B6GTGeImZXkrbFFJwQihUSujj5H6l/+5a7NxbyA1MvzNwjeTaHzdNdYovTq6ywydVtF/Kt5h7oA2KmUoajaFs=" # CODACY_PROJECT_TOKEN
  - secure: "atP4OKMKBLaixI1BiypWRxdQ1DJKpUcxQStwJpXteaZuXdkTMx31ts9WGhwwWJCjDaPJJRmWqhxTNKxJLThWFWLmBso1gHm8KDoHWBGM5jS1ua8Ly7s72HCpa7z+ABZ1/2LsoUXfQGLGDIPs1EdL/2E8OlaPSFUDFwgyquEIEm0hcKOO9q9MxjXwj8EO8OsfGt3PjiWEsh+JRaK5+hRPPVbG7TXidG84C/2cndzNSnin57LUSNkKDPoysRrQipGZQSLm12MpBagcota2HDdiuDXLHJLauNllCsr/NLnurGhwqeV3zVjPlN6z5TbZhbWvni+a8jVO9tMR3zCPs2MR++rJqXoQ4Gviy9yHQFc/RnVtCIRfCHhmh3XyhEM/Z5c1zEjhyZD1eGzr625/1F/RJLJEi0jb0kihKBpEKRgGw/ppt9BkdWQ4xJsMI8H9IQ5ZfzvRhLMXhbLDwqfyfyr3fX8pWg8T9lajEcDwnWMrYerAIF67lyQBjl3c3cGcGn909FTPGjum2PFSY7MuFfmbzzi41Y9ekssiRun4XrgNu563VtIywwuy/35N4ub1+oXS0I2PCG5XBY5uvxZbL8niqmoKiFFeyIhkMdGcbvIqA7PLapPqY5NxkY4+gRSP/eOMzMCnJv/No1ZaDV/8PW4/Q5IRxehVIIX/sXPiOvDSR58=" # BINTRAY_API_KEY
install:
- curl -o $HOME/.m2/settings.xml https://gist.githubusercontent.com/cryptobot/cf5fbd909c4782aaeeeb7c7f4a1a43da/raw/e60ee486e34ee0c79f89f947abe2c83b4290c6bb/settings.xml
- echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true'" > ~/.mavenrc
before_script:
- mvn -B --update-snapshots dependency-check:check -Pdependency-check
script:
- mvn -B clean test jacoco:report verify -Pcoverage -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
after_success:
- curl -o ~/codacy-coverage-reporter.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar
- $JAVA_HOME/bin/java -jar ~/codacy-coverage-reporter.jar report -l Java -r target/site/jacoco/jacoco.xml
cache:
  directories:
  - $HOME/.m2
deploy:
- provider: script
  script: mvn clean versions:set -DnewVersion=${TRAVIS_TAG} deploy -DskipTests -Prelease
  skip_cleanup: true
  on:
    repo: cryptomator/cryptofs
    tags: true
- provider: releases
  api_key:
    secure: MuPqDpIJweuPZnZN2jVPPeiYc56r5Hr1TP+7s+caH+/Z0ToQQbsewRZtwvN1/vsf34XGH+tPTZfzkvakNbKuqgy1H94Mtz7yEyn3zo5RvQGxe2/aI3mX//CR4EuJBBrAxqcrJgyyuElE1WrtJC/2Lc0vGStOV34bZUMpXil2MPd3vNTC1Vufp/qJDYknAXka5S+oRsogKmKvXrdtsAsfn9iRwRflMtDe7y6qD18vQPl6LkIxq+BV68z/CEgHBvaO9TlxabYcOwFCFhwVDye0XIvoewS+UZpgc1zxTOcNeRfjYzKuBwsgpa2/aE500pfHaWqwA/1vHsY0yrEIqYN7V+kA8D+QAHmMzrtbJ68nrH59et++IE/BTBND4bd5BE8IUf5Knsr1OYlP8QIUNG69sYka1Wms8sZqQiTW3hKfg6zCcB85fUY7TwVZGlRBDimj0DDcNlItuTdLMjMWn86NsxCk33r2cgy6isY9xCK+KNu7sBBbd5hOTLvmOgtSMi8+txiKth+/3DuUqj4s6kjldUUAeJv7KZ8UkbBn30E8Vl7cGPELVH6slcpcSv0xxgVNkehzYJjx0OAN5LomxJEfuVy8FFjWx8cffY/NJcNuqem0s36rNZEA5NEdYqIWL9XCLrUGytO4eBxVjfQNXjnAYUy5AKpcRrVaPswsHYQ7/XI=
  file_glob: true
  file:
  - "target/dependency-list.txt"
  - "target/*.jar"
  skip_cleanup: true
  on:
    repo: cryptomator/cryptofs
    tags: true
after_deploy:
  - "echo '{\"close\": \"1\"}' | curl --max-time 10 -X POST -u cryptobot:${BINTRAY_API_KEY} https://api.bintray.com/maven_central_sync/cryptomator/maven/cryptofs/versions/${TRAVIS_TAG}"
